baseURL = "https://drumnico.pages.dev/"
languageCode = "en-us"
title = "Drum Nico - The music of Percussionist Nico Spezzacatena"
theme = "hugo-serif-theme2"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true
    hide_view_all_services = false  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/nico-logo-mobile.svg"
    mobile_height = "36px"
    desktop = "images/logo/nico-logo.svg"
    desktop_height = "200px"
    alt = "Drum Nico"

  [params.homepage_meta_tags]
    meta_description = "Nico Spezzacatena is a multi-talented percussionist, performer, and educator from Hoboken, New Jersey. He received his BFA and MFA in world music performance from the California Institute of the Arts. Nico has been studying and researching traditional music and dance for over 25 years.In 1997, he founded Guineafia – a West African Drum and Dance Ensemble."
    meta_og_title = "Drum Nico"
    meta_og_type = "website"
    meta_og_url = "https://drumnico.pages.dev/"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Nico Spezzacatena is a multi-talented percussionist, performer, and educator from Hoboken, New Jersey. He received his BFA and MFA in world music performance from the California Institute of the Arts. Nico has been studying and researching traditional music and dance for over 25 years.In 1997, he founded Guineafia – a West African Drum and Dance Ensemble."

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Copyright 2021 <a class="zerostatic" href="https://www.drumnico.com">www.drumnico.com</a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Musical Services"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Drums For Sale"
      url = "/forsale/"
      weight = 2

  [[menu.main]]
      name = "About Me"
      url = "/about/"
      weight = 3

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
